language: go
go:
 - 1.1 
services:
 - redis-server
before_script:
 - go get labix.org/v2/mgo/bson
 - mysql -e 'create database uniqush;'
script:
 - go test -v -race github.com/uniqush/uniqush-conn/msgcache
 - go test -v -race github.com/uniqush/uniqush-conn/proto
 - go test -v -race github.com/uniqush/uniqush-conn/proto/server
 - go test -v -race github.com/uniqush/uniqush-conn/msgcenter
 - go test -v -race github.com/uniqush/uniqush-conn/config
